# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d0e671486217af4164c7415d54f2ae735852b96d6447fe9cd1a4f971d0c545f8ff09443902953254ef2a3174a8234222315dc63f6cdbdcb55ba756e8d9c1a60

test:
  secret_key_base: 6c35f948c492254adc14bb972ee1bb8299012b2033d4bd97a3214119120d29ae982616d4b07f04a34c0cfd71a115fbede4d4e33ee121b6c8fcbdc91902fa6105

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
